# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterwarz', '0002_auto_20161208_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@email.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='thisisdumb', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(default='@fartface', max_length=60),
            preserve_default=False,
        ),
    ]
